### ISSUE TITLE
Wrong path to elements.mjs

### ISSUE THREAD

**Issue by doooooooomiki** [enhance-dev/eleventy-plugin#1]
Hi Folks!
I followed your [deployment guideline](https://enhance.dev/docs/learn/deployment/11ty) for 11ty and got the following error message:

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering liquid template ./index.html (via TemplateContentRenderError)
[11ty] 2. frag.childNodes is not iterable (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: frag.childNodes is not iterable
[11ty]     at expandTemplate (/Users/username/Desktop/foldername/11ty-enhance/myproject/node_modules/@enhance/eleventy-plugin/vendor/enhance-ssr.js:7527:27)
[11ty]     at find (/Users/username/Desktop/foldername/11ty-enhance/myproject/node_modules/@enhance/eleventy-plugin/vendor/enhance-ssr.js:7451:69)
[11ty]     at processCustomElements (/Users/username/Desktop/foldername/11ty-enhance/myproject/node_modules/@enhance/eleventy-plugin/vendor/enhance-ssr.js:7458:5)
[11ty]     at html (/Users/username/Desktop/foldername/11ty-enhance/myproject/node_modules/@enhance/eleventy-plugin/vendor/enhance-ssr.js:7470:52)
[11ty]     at Object.compiler (/Users/username/Desktop/foldername/11ty-enhance/myproject/node_modules/@enhance/eleventy-plugin/plugin.js:10:18)
[11ty]     at async Template._render (/Users/username/Desktop/foldername/11ty-enhance/myproject/node_modules/@11ty/eleventy/src/TemplateContent.js:432:22)
[11ty]     at async Template.getTemplateMapContent (/Users/username/Desktop/foldername/11ty-enhance/myproject/node_modules/@11ty/eleventy/src/Template.js:1077:19)
[11ty]     at async TemplateMap.populateContentDataInMap (/Users/username/Desktop/foldername/11ty-enhance/myproject/node_modules/@11ty/eleventy/src/TemplateMap.js:461:39)
[11ty]     at async TemplateMap.cache (/Users/username/Desktop/foldername/11ty-enhance/myproject/node_modules/@11ty/eleventy/src/TemplateMap.js:360:5)
[11ty]     at async TemplateWriter._createTemplateMap (/Users/username/Desktop/foldername/11ty-enhance/myproject/node_modules/@11ty/eleventy/src/TemplateWriter.js:244:5)
[11ty] Wrote 0 files in 0.07 seconds (v1.0.2)

Apparently the path to ```elements.mjs``` could not be found (the guide wants it to be created like this: ```elements/elements.mjs```)

Inside of ```plugin.js``` there is the following line
```let pathToModule = join(process.cwd(), 'elements.mjs')```
So in this case the folder ```elements/```wasn't part of this path

The App compiled after I
- put ```elements.mjs``` into the root folder or
- after I modified the ```join()``` to ```join(process.cwd(), 'elements/elements.mjs')```

[error.txt](https://github.com/enhance-dev/eleventy-plugin/files/9483242/error.txt)

**Comment by kristoferjoseph** [comment]
Yes. We have updated the docs. The `elements.mjs` file should not be required anymore if you use a consistent naming convention with element file names.
